### ISSUE TITLE
Strider instance chokes after initial DB connection

### ISSUE THREAD

**Issue by talexand** [Strider-CD/docker-strider#12]
Log:

```
[vagrant@localhost strider-docker]$ sudo docker-compose up
Creating striderdocker_db_1...
Creating striderdocker_app_1...
Attaching to striderdocker_db_1, striderdocker_app_1
db_1  | 2015-08-26T10:55:47.610+0000 I STORAGE  [initandlisten] 
db_1  | 2015-08-26T10:55:47.611+0000 I STORAGE  [initandlisten] ** WARNING: Readahead for /data/db is set to 4096KB
db_1  | 2015-08-26T10:55:47.611+0000 I STORAGE  [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
db_1  | 2015-08-26T10:55:47.611+0000 I STORAGE  [initandlisten] **          http://dochub.mongodb.org/core/readahead
db_1  | 2015-08-26T10:55:47.611+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
db_1  | 2015-08-26T10:55:47.611+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
db_1  | 2015-08-26T10:55:47.839+0000 I JOURNAL  [durability] Durability thread started
db_1  | 2015-08-26T10:55:47.839+0000 I JOURNAL  [journal writer] Journal writer thread started
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=a485c486725c
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] 
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] 
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] db version v3.0.6
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] git version: 1ef45a23a4c5e3480ac919b28afcba3c615488f2
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] build info: Linux ip-10-233-162-213 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 BOOST_LIB_VERSION=1_49
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1  | 2015-08-26T10:55:47.841+0000 I CONTROL  [initandlisten] options: {}
db_1  | 2015-08-26T10:55:47.843+0000 I INDEX    [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
db_1  | 2015-08-26T10:55:47.918+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
db_1  | 2015-08-26T10:55:47.918+0000 I STORAGE  [FileAllocator] creating directory /data/db/_tmp
db_1  | 2015-08-26T10:55:47.920+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0 secs
db_1  | 2015-08-26T10:55:47.927+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
app_1 | Connecting to MongoDB URL: mongodb://db:27017
app_1 | 
db_1  | 2015-08-26T10:55:54.480+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.30:34184 #1 (1 connection now open)
db_1  | 2015-08-26T10:55:54.481+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.30:34185 #2 (2 connections now open)
db_1  | 2015-08-26T10:55:54.481+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.30:34186 #3 (3 connections now open)
db_1  | 2015-08-26T10:55:54.481+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.30:34187 #4 (4 connections now open)
db_1  | 2015-08-26T10:55:54.481+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.30:34188 #5 (5 connections now open)
db_1  | 2015-08-26T10:55:54.618+0000 I INDEX    [conn2] allocating new ns file /data/db/test.ns, filling with zeroes...
db_1  | 2015-08-26T10:55:54.749+0000 I STORAGE  [FileAllocator] allocating new datafile /data/db/test.0, filling with zeroes...
db_1  | 2015-08-26T10:55:54.762+0000 I STORAGE  [FileAllocator] done allocating datafile /data/db/test.0, size: 64MB,  took 0.001 secs
db_1  | 2015-08-26T10:55:54.780+0000 I INDEX    [conn2] build index on: test.jobs properties: { v: 1, key: { project: 1 }, name: "project_1", ns: "test.jobs", background: true, safe: null }
db_1  | 2015-08-26T10:55:54.781+0000 I INDEX    [conn4] build index on: test.invitecodes properties: { v: 1, unique: true, key: { code: 1 }, name: "code_1", ns: "test.invitecodes", background: true, safe: null }
db_1  | 2015-08-26T10:55:54.781+0000 I INDEX    [conn5] build index on: test.users properties: { v: 1, key: { email: 1 }, name: "email_1", ns: "test.users", background: true, safe: null }
db_1  | 2015-08-26T10:55:54.782+0000 I INDEX    [conn1] build index on: test.projects properties: { v: 1, unique: true, key: { name: 1 }, name: "name_1", ns: "test.projects", background: true, safe: null }
db_1  | 2015-08-26T10:55:54.782+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
db_1  | 2015-08-26T10:55:54.782+0000 I INDEX    [conn5] build index done.  scanned 0 total records. 0 secs
db_1  | 2015-08-26T10:55:54.782+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
db_1  | 2015-08-26T10:55:54.782+0000 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
db_1  | 2015-08-26T10:55:54.801+0000 I WRITE    [conn3] insert test.configs query: { version: 2, _id: ObjectId('55dd9b3a33abd60c00134933'), __v: 0 } ninserted:1 keyUpdates:0 writeConflicts:0 numYields:0 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, MMAPV1Journal: { acquireCount: { w: 6 } }, Database: { acquireCount: { w: 1, W: 1 }, acquireWaitCount: { w: 1, W: 1 }, timeAcquiringMicros: { w: 125643, W: 131 } }, Collection: { acquireCount: { W: 2 } }, Metadata: { acquireCount: { W: 2 } } } 126ms
db_1  | 2015-08-26T10:55:54.802+0000 I COMMAND  [conn3] command test.$cmd command: insert { insert: "configs", writeConcern: { w: 1 }, ordered: true, documents: [ { version: 2, _id: ObjectId('55dd9b3a33abd60c00134933'), __v: 0 } ] } keyUpdates:0 writeConflicts:0 numYields:0 reslen:40 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, MMAPV1Journal: { acquireCount: { w: 6 } }, Database: { acquireCount: { w: 1, W: 1 }, acquireWaitCount: { w: 1, W: 1 }, timeAcquiringMicros: { w: 125643, W: 131 } }, Collection: { acquireCount: { W: 2 } }, Metadata: { acquireCount: { W: 2 } } } 181ms
db_1  | 2015-08-26T10:55:54.803+0000 I COMMAND  [conn5] command test.$cmd command: createIndexes { createIndexes: "users", indexes: [ { name: "email_1", key: { email: 1 }, background: true, safe: null } ] } keyUpdates:0 writeConflicts:0 numYields:0 reslen:113 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, MMAPV1Journal: { acquireCount: { w: 7 } }, Database: { acquireCount: { w: 1, W: 2 }, acquireWaitCount: { w: 1, W: 2 }, timeAcquiringMicros: { w: 876, W: 180664 } }, Collection: { acquireCount: { W: 1 } }, Metadata: { acquireCount: { W: 3 } } } 184ms
db_1  | 2015-08-26T10:55:54.803+0000 I COMMAND  [conn4] command test.$cmd command: createIndexes { createIndexes: "invitecodes", indexes: [ { name: "code_1", key: { code: 1 }, unique: true, background: true, safe: null } ] } keyUpdates:0 writeConflicts:0 numYields:0 reslen:113 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, MMAPV1Journal: { acquireCount: { w: 7 } }, Database: { acquireCount: { w: 1, W: 2 }, acquireWaitCount: { w: 1, W: 2 }, timeAcquiringMicros: { w: 1351, W: 180322 } }, Collection: { acquireCount: { W: 1 } }, Metadata: { acquireCount: { W: 3 } } } 185ms
db_1  | 2015-08-26T10:55:54.803+0000 I COMMAND  [conn1] command test.$cmd command: createIndexes { createIndexes: "projects", indexes: [ { name: "name_1", key: { name: 1 }, unique: true, background: true, safe: null } ] } keyUpdates:0 writeConflicts:0 numYields:0 reslen:113 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, MMAPV1Journal: { acquireCount: { w: 6 } }, Database: { acquireCount: { w: 1, W: 2 }, acquireWaitCount: { W: 2 }, timeAcquiringMicros: { W: 161146 } }, Collection: { acquireCount: { W: 1 } }, Metadata: { acquireCount: { W: 3 } } } 164ms
db_1  | 2015-08-26T10:55:54.803+0000 I COMMAND  [conn2] command test.$cmd command: createIndexes { createIndexes: "jobs", indexes: [ { name: "project_1", key: { project: 1 }, background: true, safe: null } ] } keyUpdates:0 writeConflicts:0 numYields:0 reslen:113 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, MMAPV1Journal: { acquireCount: { w: 10 } }, Database: { acquireCount: { w: 1, W: 2 }, acquireWaitCount: { w: 1, W: 1 }, timeAcquiringMicros: { w: 1872, W: 20396 } }, Collection: { acquireCount: { W: 1 } }, Metadata: { acquireCount: { W: 5 } } } 185ms
app_1 | 
app_1 | /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
app_1 |         throw message;      
app_1 |               ^
app_1 | TypeError: Cannot read property 'length' of undefined
app_1 |     at processResults (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
app_1 |     at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
app_1 |     at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
app_1 |     at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
app_1 |     at Server.Base._callHandler (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
app_1 |     at /opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
app_1 |     at MongoReply.parseBody (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
app_1 |     at null.<anonymous> (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
app_1 |     at EventEmitter.emit (events.js:95:17)
app_1 |     at null.<anonymous> (/opt/strider/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
db_1  | 2015-08-26T10:55:55.457+0000 I NETWORK  [conn3] end connection 172.17.0.30:34186 (4 connections now open)
db_1  | 2015-08-26T10:55:55.457+0000 I NETWORK  [conn5] end connection 172.17.0.30:34188 (3 connections now open)
db_1  | 2015-08-26T10:55:55.458+0000 I NETWORK  [conn2] end connection 172.17.0.30:34185 (2 connections now open)
db_1  | 2015-08-26T10:55:55.458+0000 I NETWORK  [conn1] end connection 172.17.0.30:34184 (1 connection now open)
db_1  | 2015-08-26T10:55:55.458+0000 I NETWORK  [conn4] end connection 172.17.0.30:34187 (0 connections now open)
```

Reproduce:

1. `vagrant init centos7-base`
2. `vagrant up; vagrant-ssh`
3. Install docker, docker-compose
4. Create below docker-compose.yml file and run with `docker-compose up`

```yml
db:
  image: mongo

app:
  image: quay.io/keyvanfatehi/strider:1.6.0-pre.2
  command: bash start.sh
  ports:
    - "80:3000"
  links:
    - db
  environment:
    DB_URI: "mongodb://db:27017"
    GENERATE_ADMIN_USER: "true"
```

**Comment by gentisaliu** [comment]
+1.

Please fix.
